package HealthProtocolUK.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase;
import org.jetbrains.annotations.NotNull;
import java.util.List;
import jetbrains.mps.lang.editor.menus.MenuPart;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuItem;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuContext;
import java.util.ArrayList;
import jetbrains.mps.lang.editor.menus.substitute.ConstraintsFilteringSubstituteMenuPartDecorator;
import jetbrains.mps.lang.editor.menus.EditorMenuDescriptorBase;
import jetbrains.mps.smodel.SNodePointer;
import jetbrains.mps.lang.editor.menus.ConceptMenusPart;
import java.util.Collection;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.internal.collections.runtime.IWhereFilter;
import jetbrains.mps.internal.collections.runtime.Sequence;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.editor.menus.substitute.SimpleConceptSubstituteMenuPart;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class OutputStatus_SubstituteMenu extends SubstituteMenuBase {
  @NotNull
  @Override
  protected List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> getParts(final SubstituteMenuContext _context) {
    List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> result = new ArrayList<MenuPart<SubstituteMenuItem, SubstituteMenuContext>>();
    result.add(new ConstraintsFilteringSubstituteMenuPartDecorator(new SMP_Concepts_qijqyq_a(), CONCEPTS.OutputStatus$gj));
    return result;
  }

  @NotNull
  @Override
  public List<SubstituteMenuItem> createMenuItems(@NotNull SubstituteMenuContext context) {
    context.getEditorMenuTrace().pushTraceInfo();
    context.getEditorMenuTrace().setDescriptor(new EditorMenuDescriptorBase("default substitute menu for " + "OutputStatus", new SNodePointer("r:12896a7d-0e31-4fe4-9e9c-c4260ead99f1(HealthProtocolUK.editor)", "1314835973984064475")));
    try {
      return super.createMenuItems(context);
    } finally {
      context.getEditorMenuTrace().popTraceInfo();
    }
  }


  public class SMP_Concepts_qijqyq_a extends ConceptMenusPart<SubstituteMenuItem, SubstituteMenuContext> {
    protected Collection getConcepts(SubstituteMenuContext _context) {
      Iterable<SNode> measurement = SLinkOperations.collect(SLinkOperations.getChildren(SNodeOperations.getNodeAncestor(_context.getParentNode(), CONCEPTS.EvaluationEntry$J9, false, false), LINKS.range$dYHx), LINKS.measurement$O6MX);
      List<SConcept> list = ListSequence.fromList(SConceptOperations.getAllSubConcepts2(CONCEPTS.OutputStatus$gj, _context.getModel())).where(new IWhereFilter<SConcept>() {
        public boolean accept(SConcept it) {
          return !(it.isAbstract());
        }
      }).toListSequence();

      if (Sequence.fromIterable(measurement).any(new IWhereFilter<SNode>() {
        public boolean accept(SNode it) {
          return SNodeOperations.isInstanceOf(it, CONCEPTS.GlucoseMeasurement$Bh);
        }
      })) {
        list = (List<SConcept>) ListSequence.fromList(list).where(new IWhereFilter<SConcept>() {
          public boolean accept(SConcept it) {
            return !(SConceptOperations.isExactly(SNodeOperations.asSConcept(it), CONCEPTS.GoodOutputStatus$gM));
          }
        }).toListSequence();
      }
      return list;
    }

    @NotNull
    @Override
    public List<SubstituteMenuItem> createItems(SubstituteMenuContext _context) {
      _context.getEditorMenuTrace().pushTraceInfo();
      _context.getEditorMenuTrace().setDescriptor(new EditorMenuDescriptorBase("simple actions for the list of concepts", new SNodePointer("r:12896a7d-0e31-4fe4-9e9c-c4260ead99f1(HealthProtocolUK.editor)", "1314835973984064479")));
      try {
        return super.createItems(_context);
      } finally {
        _context.getEditorMenuTrace().popTraceInfo();
      }
    }
    @Override
    protected Collection<SubstituteMenuItem> createItemsForConcept(final SubstituteMenuContext _context, final SAbstractConcept concept) {
      return new SimpleConceptSubstituteMenuPart(concept) {
        @NotNull
        @Override
        public List<SubstituteMenuItem> createItems(SubstituteMenuContext context) {
          context.getEditorMenuTrace().pushTraceInfo();
          context.getEditorMenuTrace().setDescriptor(new EditorMenuDescriptorBase("simple action for concept: " + concept.getName(), null));
          try {
            return super.createItems(context);
          } finally {
            context.getEditorMenuTrace().popTraceInfo();
          }
        }
      }.createItems(_context);
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept OutputStatus$gj = MetaAdapterFactory.getConcept(0x270a52d288a4279L, 0xba126f9a2781f5f4L, 0x2d4758520b357a96L, "HealthProtocolUK.structure.OutputStatus");
    /*package*/ static final SConcept EvaluationEntry$J9 = MetaAdapterFactory.getConcept(0x270a52d288a4279L, 0xba126f9a2781f5f4L, 0x752b16ad9c803e24L, "HealthProtocolUK.structure.EvaluationEntry");
    /*package*/ static final SConcept GoodOutputStatus$gM = MetaAdapterFactory.getConcept(0x270a52d288a4279L, 0xba126f9a2781f5f4L, 0x2d4758520b357a97L, "HealthProtocolUK.structure.GoodOutputStatus");
    /*package*/ static final SConcept GlucoseMeasurement$Bh = MetaAdapterFactory.getConcept(0x270a52d288a4279L, 0xba126f9a2781f5f4L, 0x752b16ad9c803e74L, "HealthProtocolUK.structure.GlucoseMeasurement");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink range$dYHx = MetaAdapterFactory.getContainmentLink(0x270a52d288a4279L, 0xba126f9a2781f5f4L, 0x752b16ad9c803e24L, 0x654b9e6c3a64fe4aL, "range");
    /*package*/ static final SContainmentLink measurement$O6MX = MetaAdapterFactory.getContainmentLink(0x270a52d288a4279L, 0xba126f9a2781f5f4L, 0x21db3c3dba9f59e0L, 0x21db3c3dba9f59e4L, "measurement");
  }
}
