package HealthProtocolUK.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_ReminderTypeEnum extends EnumerationDescriptorBase {

  public EnumerationDescriptor_ReminderTypeEnum() {
    super(0x270a52d288a4279L, 0xba126f9a2781f5f4L, 0x654b9e6c3a64fe6fL, "ReminderTypeEnum", "r:78547a60-8242-4ad0-8b5f-7fb3e8bb1328(HealthProtocolUK.structure)/7299101808757374575");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_WEEKLY_0 = new EnumerationDescriptor.MemberDescriptor("WEEKLY", "every week", 0x654b9e6c3a64fe70L, "r:78547a60-8242-4ad0-8b5f-7fb3e8bb1328(HealthProtocolUK.structure)/7299101808757374576");
  private final EnumerationDescriptor.MemberDescriptor myMember_YEARLY_0 = new EnumerationDescriptor.MemberDescriptor("YEARLY", "every year", 0x654b9e6c3a64fe71L, "r:78547a60-8242-4ad0-8b5f-7fb3e8bb1328(HealthProtocolUK.structure)/7299101808757374577");
  private final EnumerationDescriptor.MemberDescriptor myMember_DAILY_0 = new EnumerationDescriptor.MemberDescriptor("DAILY", "every day", 0x654b9e6c3a64fe74L, "r:78547a60-8242-4ad0-8b5f-7fb3e8bb1328(HealthProtocolUK.structure)/7299101808757374580");
  private final EnumerationDescriptor.MemberDescriptor myMember_MONTHLY_0 = new EnumerationDescriptor.MemberDescriptor("MONTHLY", "every month", 0x654b9e6c3a64fe78L, "r:78547a60-8242-4ad0-8b5f-7fb3e8bb1328(HealthProtocolUK.structure)/7299101808757374584");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x270a52d288a4279L, 0xba126f9a2781f5f4L, 0x654b9e6c3a64fe6fL, 0x654b9e6c3a64fe70L, 0x654b9e6c3a64fe71L, 0x654b9e6c3a64fe74L, 0x654b9e6c3a64fe78L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_WEEKLY_0, myMember_YEARLY_0, myMember_DAILY_0, myMember_MONTHLY_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "WEEKLY":
        return myMember_WEEKLY_0;
      case "YEARLY":
        return myMember_YEARLY_0;
      case "DAILY":
        return myMember_DAILY_0;
      case "MONTHLY":
        return myMember_MONTHLY_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
