package HealthProtocolUK.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_OutputStatusEnum extends EnumerationDescriptorBase {

  public EnumerationDescriptor_OutputStatusEnum() {
    super(0x270a52d288a4279L, 0xba126f9a2781f5f4L, 0x654b9e6c3a64fe5eL, "OutputStatusEnum", "r:78547a60-8242-4ad0-8b5f-7fb3e8bb1328(HealthProtocolUK.structure)/7299101808757374558");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_GOOD_0 = new EnumerationDescriptor.MemberDescriptor("GOOD", "Good", 0x654b9e6c3a64fe5fL, "r:78547a60-8242-4ad0-8b5f-7fb3e8bb1328(HealthProtocolUK.structure)/7299101808757374559");
  private final EnumerationDescriptor.MemberDescriptor myMember_NORMAL_0 = new EnumerationDescriptor.MemberDescriptor("NORMAL", "Normal", 0x654b9e6c3a64fe60L, "r:78547a60-8242-4ad0-8b5f-7fb3e8bb1328(HealthProtocolUK.structure)/7299101808757374560");
  private final EnumerationDescriptor.MemberDescriptor myMember_CHECK_RISK_FACTORS_0 = new EnumerationDescriptor.MemberDescriptor("CHECK_RISK_FACTORS", "Check risk factors", 0x654b9e6c3a64fe63L, "r:78547a60-8242-4ad0-8b5f-7fb3e8bb1328(HealthProtocolUK.structure)/7299101808757374563");
  private final EnumerationDescriptor.MemberDescriptor myMember_ASK_MEDICAL_HELP_0 = new EnumerationDescriptor.MemberDescriptor("ASK_MEDICAL_HELP", "Ask for medical help", 0x654b9e6c3a64fe67L, "r:78547a60-8242-4ad0-8b5f-7fb3e8bb1328(HealthProtocolUK.structure)/7299101808757374567");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x270a52d288a4279L, 0xba126f9a2781f5f4L, 0x654b9e6c3a64fe5eL, 0x654b9e6c3a64fe5fL, 0x654b9e6c3a64fe60L, 0x654b9e6c3a64fe63L, 0x654b9e6c3a64fe67L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_GOOD_0, myMember_NORMAL_0, myMember_CHECK_RISK_FACTORS_0, myMember_ASK_MEDICAL_HELP_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "GOOD":
        return myMember_GOOD_0;
      case "NORMAL":
        return myMember_NORMAL_0;
      case "CHECK_RISK_FACTORS":
        return myMember_CHECK_RISK_FACTORS_0;
      case "ASK_MEDICAL_HELP":
        return myMember_ASK_MEDICAL_HELP_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
