package HealthProtocolUK.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_MeasurementUnit extends EnumerationDescriptorBase {

  public EnumerationDescriptor_MeasurementUnit() {
    super(0x270a52d288a4279L, 0xba126f9a2781f5f4L, 0x752b16ad9c803e2dL, "MeasurementUnit", "r:78547a60-8242-4ad0-8b5f-7fb3e8bb1328(HealthProtocolUK.structure)/8442866861346930221");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_KILOGRAM_0 = new EnumerationDescriptor.MemberDescriptor("KILOGRAM", "kg", 0x752b16ad9c803e2eL, "r:78547a60-8242-4ad0-8b5f-7fb3e8bb1328(HealthProtocolUK.structure)/8442866861346930222");
  private final EnumerationDescriptor.MemberDescriptor myMember_MOL_PER_LITRE_0 = new EnumerationDescriptor.MemberDescriptor("MOL_PER_LITRE", "mmol/L", 0x654b9e6c3a64d9e9L, "r:78547a60-8242-4ad0-8b5f-7fb3e8bb1328(HealthProtocolUK.structure)/7299101808757365225");
  private final EnumerationDescriptor.MemberDescriptor myMember_BEATS_PER_MINUTE_0 = new EnumerationDescriptor.MemberDescriptor("BEATS_PER_MINUTE", "bpm", 0x4c693a05b32504d0L, "r:78547a60-8242-4ad0-8b5f-7fb3e8bb1328(HealthProtocolUK.structure)/5505995815591937232");
  private final EnumerationDescriptor.MemberDescriptor myMember_MERCURY_MM_0 = new EnumerationDescriptor.MemberDescriptor("MERCURY_MM", "mmHG", 0x4c693a05b32504d5L, "r:78547a60-8242-4ad0-8b5f-7fb3e8bb1328(HealthProtocolUK.structure)/5505995815591937237");
  private final EnumerationDescriptor.MemberDescriptor myMember_CELSIUS_DEGREE_0 = new EnumerationDescriptor.MemberDescriptor("CELSIUS_DEGREE", "°C", 0xbb4c0906ddcf21L, "r:78547a60-8242-4ad0-8b5f-7fb3e8bb1328(HealthProtocolUK.structure)/52719422298509089");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x270a52d288a4279L, 0xba126f9a2781f5f4L, 0x752b16ad9c803e2dL, 0x752b16ad9c803e2eL, 0x654b9e6c3a64d9e9L, 0x4c693a05b32504d0L, 0x4c693a05b32504d5L, 0xbb4c0906ddcf21L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_KILOGRAM_0, myMember_MOL_PER_LITRE_0, myMember_BEATS_PER_MINUTE_0, myMember_MERCURY_MM_0, myMember_CELSIUS_DEGREE_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "KILOGRAM":
        return myMember_KILOGRAM_0;
      case "MOL_PER_LITRE":
        return myMember_MOL_PER_LITRE_0;
      case "BEATS_PER_MINUTE":
        return myMember_BEATS_PER_MINUTE_0;
      case "MERCURY_MM":
        return myMember_MERCURY_MM_0;
      case "CELSIUS_DEGREE":
        return myMember_CELSIUS_DEGREE_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
