package HealthProtocolUK.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_MeasurementType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_MeasurementType() {
    super(0x270a52d288a4279L, 0xba126f9a2781f5f4L, 0x654b9e6c3a64d9dcL, "MeasurementType", "r:78547a60-8242-4ad0-8b5f-7fb3e8bb1328(HealthProtocolUK.structure)/7299101808757365212");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_WEIGTH_0 = new EnumerationDescriptor.MemberDescriptor("WEIGTH", "WEIGTH", 0x654b9e6c3a64d9ddL, "r:78547a60-8242-4ad0-8b5f-7fb3e8bb1328(HealthProtocolUK.structure)/7299101808757365213");
  private final EnumerationDescriptor.MemberDescriptor myMember_GLUCOSE_0 = new EnumerationDescriptor.MemberDescriptor("GLUCOSE", "GLUCOSE", 0x654b9e6c3a64d9deL, "r:78547a60-8242-4ad0-8b5f-7fb3e8bb1328(HealthProtocolUK.structure)/7299101808757365214");
  private final EnumerationDescriptor.MemberDescriptor myMember_PULSE_0 = new EnumerationDescriptor.MemberDescriptor("PULSE", "PULSE", 0x4c693a05b32504bdL, "r:78547a60-8242-4ad0-8b5f-7fb3e8bb1328(HealthProtocolUK.structure)/5505995815591937213");
  private final EnumerationDescriptor.MemberDescriptor myMember_TEMP_0 = new EnumerationDescriptor.MemberDescriptor("TEMP", "TEMP", 0x4c693a05b32504c1L, "r:78547a60-8242-4ad0-8b5f-7fb3e8bb1328(HealthProtocolUK.structure)/5505995815591937217");
  private final EnumerationDescriptor.MemberDescriptor myMember_PRESSURE_0 = new EnumerationDescriptor.MemberDescriptor("PRESSURE", "PRESSURE", 0x4c693a05b32504c6L, "r:78547a60-8242-4ad0-8b5f-7fb3e8bb1328(HealthProtocolUK.structure)/5505995815591937222");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x270a52d288a4279L, 0xba126f9a2781f5f4L, 0x654b9e6c3a64d9dcL, 0x654b9e6c3a64d9ddL, 0x654b9e6c3a64d9deL, 0x4c693a05b32504bdL, 0x4c693a05b32504c1L, 0x4c693a05b32504c6L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_WEIGTH_0, myMember_GLUCOSE_0, myMember_PULSE_0, myMember_TEMP_0, myMember_PRESSURE_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "WEIGTH":
        return myMember_WEIGTH_0;
      case "GLUCOSE":
        return myMember_GLUCOSE_0;
      case "PULSE":
        return myMember_PULSE_0;
      case "TEMP":
        return myMember_TEMP_0;
      case "PRESSURE":
        return myMember_PRESSURE_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
