package HealthProtocolUK.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBehaviorAspectDescriptor;
import jetbrains.mps.core.aspects.behaviour.api.BHDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public final class BehaviorAspectDescriptor extends BaseBehaviorAspectDescriptor {
  private final BHDescriptor myDiastolicPressureMeasurement__BehaviorDescriptor = new DiastolicPressureMeasurement__BehaviorDescriptor();
  private final BHDescriptor myBloodPressureMeasurement__BehaviorDescriptor = new BloodPressureMeasurement__BehaviorDescriptor();
  private final BHDescriptor myMeasurement__BehaviorDescriptor = new Measurement__BehaviorDescriptor();
  private final BHDescriptor myWeightMeasurement__BehaviorDescriptor = new WeightMeasurement__BehaviorDescriptor();
  private final BHDescriptor myTemperatureMeasurement__BehaviorDescriptor = new TemperatureMeasurement__BehaviorDescriptor();
  private final BHDescriptor mySystolicPressureMeasurement__BehaviorDescriptor = new SystolicPressureMeasurement__BehaviorDescriptor();
  private final BHDescriptor myPulseMeasurement__BehaviorDescriptor = new PulseMeasurement__BehaviorDescriptor();
  private final BHDescriptor myGlucoseMeasurement__BehaviorDescriptor = new GlucoseMeasurement__BehaviorDescriptor();

  public BehaviorAspectDescriptor() {
  }

  @Nullable
  public BHDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return myBloodPressureMeasurement__BehaviorDescriptor;
      case 1:
        return myDiastolicPressureMeasurement__BehaviorDescriptor;
      case 2:
        return myGlucoseMeasurement__BehaviorDescriptor;
      case 3:
        return myMeasurement__BehaviorDescriptor;
      case 4:
        return myPulseMeasurement__BehaviorDescriptor;
      case 5:
        return mySystolicPressureMeasurement__BehaviorDescriptor;
      case 6:
        return myTemperatureMeasurement__BehaviorDescriptor;
      case 7:
        return myWeightMeasurement__BehaviorDescriptor;
      default:
    }
    return null;
  }
  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x270a52d288a4279L, 0xba126f9a2781f5f4L, 0x21db3c3dba9f59dfL), MetaIdFactory.conceptId(0x270a52d288a4279L, 0xba126f9a2781f5f4L, 0x21db3c3dba9f59deL), MetaIdFactory.conceptId(0x270a52d288a4279L, 0xba126f9a2781f5f4L, 0x752b16ad9c803e74L), MetaIdFactory.conceptId(0x270a52d288a4279L, 0xba126f9a2781f5f4L, 0x752b16ad9c803e23L), MetaIdFactory.conceptId(0x270a52d288a4279L, 0xba126f9a2781f5f4L, 0x752b16ad9c803e73L), MetaIdFactory.conceptId(0x270a52d288a4279L, 0xba126f9a2781f5f4L, 0x752b16ad9c803e72L), MetaIdFactory.conceptId(0x270a52d288a4279L, 0xba126f9a2781f5f4L, 0x752b16ad9c803e71L), MetaIdFactory.conceptId(0x270a52d288a4279L, 0xba126f9a2781f5f4L, 0x752b16ad9c803e70L)).seal();
}
